"use client";

import { use } from "react";
import { DashboardLayout } from "@/components/dashboard-layout";
import { mockEntrepreneurs } from "@/lib/mock-data";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { TrustBadge } from "@/components/community/trust-badge";
import { ConnectActions } from "@/components/community/connect-actions";
import { Badge } from "@/components/ui/badge";
import { BrainCircuit, Target, TrendingUp, AlertTriangle, FileText, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function StartupProfilePage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = use(params);
  
  // In a real app we'd fetch this from via the API.
  // Using dummy data if it matches, otherwise fallback to the first one for demo purposes.
  const profile = mockEntrepreneurs.find(e => e.id === resolvedParams.id) || mockEntrepreneurs[0];

  return (
    <DashboardLayout>
      <div className="max-w-5xl mx-auto space-y-8 pb-12">
        
        {/* Header Profile Section */}
        <div className="relative rounded-2xl overflow-hidden glass-card border border-purple-500/20">
          <div className="h-32 bg-gradient-to-r from-purple-900/50 to-blue-900/50 w-full" />
          <div className="px-8 pb-8 pt-0 relative">
            <div className="flex flex-col md:flex-row gap-6 items-start md:items-end -mt-16 mb-4">
              <Avatar className="h-32 w-32 border-4 border-background shadow-xl">
                <AvatarImage src={profile.photoUrl} alt={profile.name} />
                <AvatarFallback>{profile.name[0]}</AvatarFallback>
              </Avatar>
              <div className="flex-1 pb-2">
                <h1 className="text-3xl font-bold">{profile.startupName}</h1>
                <p className="text-lg text-muted-foreground">Founded by {profile.name}</p>
              </div>
              <div className="pb-2 flex gap-3 w-full md:w-auto">
                 <ConnectActions type="founder" />
              </div>
            </div>
            
            <div className="flex flex-wrap gap-3 mt-6">
               {profile.verifiedFounder && <TrustBadge type="verified-founder" />}
               {profile.score > 80 && <TrustBadge type="ai-recommended" />}
               <Badge variant="outline" className="text-sm bg-background/50 border-border/50">{profile.industry}</Badge>
               <Badge variant="outline" className="text-sm bg-background/50 border-border/50">{profile.startupStage}</Badge>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Main Info Column */}
          <div className="col-span-1 lg:col-span-2 space-y-8">
            <Card className="glass-card">
              <CardHeader>
                <CardTitle className="text-xl">Pitch Summary</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-foreground/90 leading-relaxed text-lg">{profile.pitchSummary}</p>
                <div className="mt-6 p-4 rounded-xl border border-purple-500/20 bg-purple-500/5 flex items-start gap-4">
                   <Target className="w-8 h-8 text-purple-400 shrink-0" />
                   <div>
                     <h4 className="font-semibold text-purple-300">Traction & Growth</h4>
                     <p className="text-sm mt-1">{profile.tractionMetrics} • {profile.monthlyGrowth} month-over-month growth.</p>
                   </div>
                </div>
              </CardContent>
            </Card>

            <Card className="glass-card border-blue-500/20">
              <CardHeader className="flex flex-row justify-between items-center pb-2">
                <CardTitle className="text-xl flex items-center gap-2">
                  <BrainCircuit className="text-blue-400" />
                  AI Success Analysis
                </CardTitle>
                <div className="bg-gradient-to-r from-purple-500 to-blue-500 text-white font-black px-4 py-1.5 rounded-full text-xl shadow-lg">
                  {profile.score}/100
                </div>
              </CardHeader>
              <CardContent>
                 <p className="text-sm text-muted-foreground mb-6">Generated by the core ML prediction pipeline based on market, team, and traction signals.</p>
                 
                 <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-6">
                    <div className="bg-background/50 border border-border/50 p-4 rounded-xl">
                      <div className="text-xs text-muted-foreground uppercase tracking-wider mb-1">Growth Prob.</div>
                      <div className="text-2xl font-bold flex items-center gap-2">
                        {profile.growthProbability}%
                        <TrendingUp className="w-4 h-4 text-emerald-500" />
                      </div>
                    </div>
                    <div className="bg-background/50 border border-border/50 p-4 rounded-xl">
                      <div className="text-xs text-muted-foreground uppercase tracking-wider mb-1">Readiness</div>
                      <div className="text-lg font-bold text-blue-400">{profile.investmentReadiness}</div>
                    </div>
                    <div className="bg-background/50 border border-border/50 p-4 rounded-xl">
                      <div className="text-xs text-muted-foreground uppercase tracking-wider mb-1">Risk Level</div>
                      <div className={`text-lg font-bold flex items-center gap-2 ${profile.riskLevel === 'High' ? 'text-amber-500' : 'text-emerald-500'}`}>
                        {profile.riskLevel}
                        {profile.riskLevel === 'High' && <AlertTriangle className="w-4 h-4" />}
                      </div>
                    </div>
                 </div>

                 <div className="bg-muted/30 p-5 rounded-xl border border-border/30">
                    <h4 className="font-semibold mb-2 flex items-center gap-2">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400" /> AI Recommendation
                    </h4>
                    <p className="text-sm leading-relaxed text-foreground/80">{profile.aiRecommendation}</p>
                 </div>
              </CardContent>
            </Card>
          </div>

          {/* Sidebar Info Column */}
          <div className="col-span-1 space-y-6">
            <Card className="glass-card">
              <CardHeader>
                <CardTitle className="text-lg">Quick Facts</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <div className="text-sm text-muted-foreground">Market Size</div>
                  <div className="font-semibold">{profile.marketSize}</div>
                </div>
                <div>
                  <div className="text-sm text-muted-foreground">Team Size</div>
                  <div className="font-semibold">{profile.teamSize} employees</div>
                </div>
                <div>
                  <div className="text-sm text-muted-foreground">Revenue Status</div>
                  <div className="font-semibold">{profile.revenueStatus}</div>
                </div>
              </CardContent>
            </Card>

             <Card className="glass-card">
              <CardHeader>
                <CardTitle className="text-lg">Documents</CardTitle>
              </CardHeader>
              <CardContent>
                <Button variant="outline" className="w-full justify-start h-12 bg-background/50">
                  <FileText className="w-5 h-5 mr-3 text-purple-400" />
                  Pitch Deck (PDF)
                </Button>
              </CardContent>
            </Card>
          </div>

        </div>
      </div>
    </DashboardLayout>
  );
}
