import { InvestorProfile, EntrepreneurProfile, SocialPost, StartupMatch } from "@/types/community";

export const mockInvestors: InvestorProfile[] = [
  { id: "inv-001", name: "Alexia Rossi", photoUrl: "https://i.pravatar.cc/150?u=alexiarossi", title: "Partner", firm: "Apex Ventures", verified: true, investmentDomains: ["AI", "SaaS", "FinTech"], preferredStage: ["Seed", "Series A"], ticketSizeMin: "$500k", ticketSizeMax: "$3M", preferredMarket: "Global", preferredGeography: "North America, Europe", portfolioStartups: 24, credibilityScore: 98, responseRate: "85%", successfulInvestments: 8 },
  { id: "inv-002", name: "Marcus Chen", photoUrl: "https://i.pravatar.cc/150?u=marcuschen", title: "Angel Investor", firm: "Independent", verified: true, investmentDomains: ["HealthTech", "EdTech", "Consumer"], preferredStage: ["Pre-seed", "Seed"], ticketSizeMin: "$50k", ticketSizeMax: "$250k", preferredMarket: "B2C", preferredGeography: "Asia, North America", portfolioStartups: 15, credibilityScore: 89, responseRate: "92%", successfulInvestments: 3 },
  { id: "inv-003", name: "Daniel Kapoor", photoUrl: "https://i.pravatar.cc/150?u=danielk", title: "Managing Director", firm: "Kapoor Capital", verified: true, investmentDomains: ["FinTech", "Crypto"], preferredStage: ["Series A", "Series B"], ticketSizeMin: "$1M", ticketSizeMax: "$5M", preferredMarket: "B2B", preferredGeography: "Global", portfolioStartups: 42, credibilityScore: 95, responseRate: "70%", successfulInvestments: 12 },
  { id: "inv-004", name: "Neha Malhotra", photoUrl: "https://i.pravatar.cc/150?u=neham", title: "Growth Partner", firm: "Elevate Fund", verified: true, investmentDomains: ["D2C", "E-commerce"], preferredStage: ["Seed"], ticketSizeMin: "$200k", ticketSizeMax: "$1M", preferredMarket: "B2C", preferredGeography: "India, US", portfolioStartups: 31, credibilityScore: 91, responseRate: "88%", successfulInvestments: 6 },
  { id: "inv-005", name: "Jason Reed", photoUrl: "https://i.pravatar.cc/150?u=jasonr", title: "Angel Investor", firm: "Reed Sync", verified: true, investmentDomains: ["SaaS", "DevTools"], preferredStage: ["Pre-seed"], ticketSizeMin: "$25k", ticketSizeMax: "$150k", preferredMarket: "B2B", preferredGeography: "US", portfolioStartups: 12, credibilityScore: 84, responseRate: "95%", successfulInvestments: 2 },
  { id: "inv-006", name: "Priya Mehta", photoUrl: "https://i.pravatar.cc/150?u=priyam", title: "General Partner", firm: "NextGen VC", verified: true, investmentDomains: ["ClimateTech", "AI"], preferredStage: ["Seed", "Series A"], ticketSizeMin: "$500k", ticketSizeMax: "$2M", preferredMarket: "B2B", preferredGeography: "Europe, India", portfolioStartups: 18, credibilityScore: 97, responseRate: "80%", successfulInvestments: 5 },
  { id: "inv-007", name: "Rohan Bansal", photoUrl: "https://i.pravatar.cc/150?u=rohanb", title: "Venture Partner", firm: "Bansal Family Office", verified: false, investmentDomains: ["Real Estate Tech", "FinTech"], preferredStage: ["Series A"], ticketSizeMin: "$1M", ticketSizeMax: "$10M", preferredMarket: "Global", preferredGeography: "UAE, India", portfolioStartups: 8, credibilityScore: 76, responseRate: "65%", successfulInvestments: 1 },
  { id: "inv-008", name: "Olivia Stein", photoUrl: "https://i.pravatar.cc/150?u=olivia", title: "Partner", firm: "Blue Horizon", verified: true, investmentDomains: ["HealthTech", "BioTech"], preferredStage: ["Series A", "Series B"], ticketSizeMin: "$2M", ticketSizeMax: "$8M", preferredMarket: "B2B", preferredGeography: "US", portfolioStartups: 22, credibilityScore: 94, responseRate: "75%", successfulInvestments: 4 },
  { id: "inv-009", name: "David Wu", photoUrl: "https://i.pravatar.cc/150?u=davidw", title: "Angel Investor", firm: "Independent", verified: true, investmentDomains: ["Gaming", "Consumer"], preferredStage: ["Pre-seed", "Seed"], ticketSizeMin: "$10k", ticketSizeMax: "$100k", preferredMarket: "B2C", preferredGeography: "Asia", portfolioStartups: 45, credibilityScore: 88, responseRate: "98%", successfulInvestments: 14 },
  { id: "inv-010", name: "Samantha Lee", photoUrl: "https://i.pravatar.cc/150?u=samantha", title: "Managing Partner", firm: "Lee & Co Ventures", verified: true, investmentDomains: ["SaaS", "HR Tech"], preferredStage: ["Seed"], ticketSizeMin: "$250k", ticketSizeMax: "$750k", preferredMarket: "B2B", preferredGeography: "North America", portfolioStartups: 19, credibilityScore: 92, responseRate: "82%", successfulInvestments: 5 },
  { id: "inv-011", name: "Elena Rostova", photoUrl: "https://i.pravatar.cc/150?u=elena", title: "Partner", firm: "European Tech Fund", verified: true, investmentDomains: ["DeepTech", "AI"], preferredStage: ["Series A"], ticketSizeMin: "$1M", ticketSizeMax: "$4M", preferredMarket: "B2B", preferredGeography: "Europe", portfolioStartups: 14, credibilityScore: 89, responseRate: "70%", successfulInvestments: 3 },
  { id: "inv-012", name: "Omar Farooq", photoUrl: "https://i.pravatar.cc/150?u=omar", title: "Angel Investor", firm: "Independent", verified: false, investmentDomains: ["FinTech", "Logistics"], preferredStage: ["Seed"], ticketSizeMin: "$50k", ticketSizeMax: "$300k", preferredMarket: "Global", preferredGeography: "MENA, South Asia", portfolioStartups: 9, credibilityScore: 81, responseRate: "85%", successfulInvestments: 2 },
  { id: "inv-013", name: "Julia Grant", photoUrl: "https://i.pravatar.cc/150?u=julia", title: "Principal", firm: "Grant Associates", verified: true, investmentDomains: ["EdTech", "Creator Economy"], preferredStage: ["Pre-seed"], ticketSizeMin: "$25k", ticketSizeMax: "$200k", preferredMarket: "B2C", preferredGeography: "North America", portfolioStartups: 26, credibilityScore: 90, responseRate: "90%", successfulInvestments: 7 },
  { id: "inv-014", name: "Ahmed Kahn", photoUrl: "https://i.pravatar.cc/150?u=ahmed", title: "GP", firm: "Kahn Ventures", verified: true, investmentDomains: ["PropTech", "SaaS"], preferredStage: ["Seed", "Series A"], ticketSizeMin: "$500k", ticketSizeMax: "$2M", preferredMarket: "B2B", preferredGeography: "UK, MENA", portfolioStartups: 11, credibilityScore: 87, responseRate: "78%", successfulInvestments: 2 },
  { id: "inv-015", name: "Isabella Cruz", photoUrl: "https://i.pravatar.cc/150?u=isabella", title: "Partner", firm: "Latam Future Fund", verified: true, investmentDomains: ["FinTech", "AgriTech"], preferredStage: ["Series A"], ticketSizeMin: "$1M", ticketSizeMax: "$3M", preferredMarket: "B2B", preferredGeography: "Latin America", portfolioStartups: 7, credibilityScore: 83, responseRate: "88%", successfulInvestments: 1 },
  { id: "inv-016", name: "Michael Chang", photoUrl: "https://i.pravatar.cc/150?u=michael", title: "Head of Ventures", firm: "TechCorp CVC", verified: true, investmentDomains: ["AI", "Cloud Infrastructure"], preferredStage: ["Series B"], ticketSizeMin: "$3M", ticketSizeMax: "$10M", preferredMarket: "Enterprise", preferredGeography: "US", portfolioStartups: 34, credibilityScore: 96, responseRate: "60%", successfulInvestments: 11 }
];

export const mockEntrepreneurs: EntrepreneurProfile[] = [
  { id: "ent-001", name: "Sarah Jenkins", photoUrl: "https://i.pravatar.cc/150?u=sarahj", startupName: "NexusAI", startupStage: "Seed", pitchSummary: "Automating B2B sales development using LLMs.", industry: "AI / SaaS", marketSize: "$12B SAM", tractionMetrics: "$15k MRR", teamSize: 6, revenueStatus: "Post-revenue", monthlyGrowth: "22%", score: 87, growthProbability: 82, investmentReadiness: "High", riskLevel: "Medium", aiRecommendation: "High probability of Series A within 12 months. Recommend introductory meeting.", verifiedFounder: true },
  { id: "ent-002", name: "David Kim", photoUrl: "https://i.pravatar.cc/150?u=davidk", startupName: "MediSync", startupStage: "Pre-seed", pitchSummary: "Unified patient data platform connecting local clinics.", industry: "HealthTech", marketSize: "$5B SAM", tractionMetrics: "12 pilot clinics", teamSize: 3, revenueStatus: "Pre-revenue", monthlyGrowth: "N/A", score: 65, growthProbability: 55, investmentReadiness: "Moderate", riskLevel: "High", aiRecommendation: "Monitor for 3 months.", verifiedFounder: true },
  { id: "ent-003", name: "Aarav Patel", photoUrl: "https://i.pravatar.cc/150?u=aarav", startupName: "FinPulse", startupStage: "Series A", pitchSummary: "API first payment gateway for Southeast Asia.", industry: "FinTech", marketSize: "$25B SAM", tractionMetrics: "$150k MRR", teamSize: 24, revenueStatus: "Post-revenue", monthlyGrowth: "15%", score: 92, growthProbability: 89, investmentReadiness: "High", riskLevel: "Low", aiRecommendation: "Strong traction in an expanding market. Ready for Series A scaling.", verifiedFounder: true },
  { id: "ent-004", name: "Chloe Smith", photoUrl: "https://i.pravatar.cc/150?u=chloe", startupName: "LearnLoop", startupStage: "Seed", pitchSummary: "AI tutor that adapts to neurodivergent learning patterns.", industry: "EdTech", marketSize: "$8B SAM", tractionMetrics: "5k active users", teamSize: 8, revenueStatus: "Post-revenue", monthlyGrowth: "30%", score: 78, growthProbability: 72, investmentReadiness: "Moderate", riskLevel: "Medium", aiRecommendation: "Good viral user growth, needs clearer monetization strategy.", verifiedFounder: true },
  { id: "ent-005", name: "Luis Garcia", photoUrl: "https://i.pravatar.cc/150?u=luis", startupName: "AgroSense", startupStage: "Pre-seed", pitchSummary: "IoT soil monitoring for smallholder farmers.", industry: "AgriTech", marketSize: "$3B SAM", tractionMetrics: "50 farms", teamSize: 4, revenueStatus: "Pre-revenue", monthlyGrowth: "10%", score: 60, growthProbability: 45, investmentReadiness: "Low", riskLevel: "High", aiRecommendation: "Hardware dependency increases risk. Proceed with caution.", verifiedFounder: false },
  { id: "ent-006", name: "Emma Watson", photoUrl: "https://i.pravatar.cc/150?u=emma", startupName: "CreatorKit", startupStage: "Seed", pitchSummary: "All-in-one financial dashboard for YouTube/TikTok creators.", industry: "FinTech / Creator Economy", marketSize: "$15B SAM", tractionMetrics: "$20k MRR", teamSize: 5, revenueStatus: "Post-revenue", monthlyGrowth: "25%", score: 85, growthProbability: 80, investmentReadiness: "High", riskLevel: "Low", aiRecommendation: "Highly engaged niche. Solid unit economics.", verifiedFounder: true },
  { id: "ent-007", name: "Hiroshi Tanaka", photoUrl: "https://i.pravatar.cc/150?u=hiroshi", startupName: "Polymer3D", startupStage: "Series A", pitchSummary: "Next-gen 3D printing resin that cures 10x faster.", industry: "DeepTech / Materials", marketSize: "$10B SAM", tractionMetrics: "$80k MRR", teamSize: 18, revenueStatus: "Post-revenue", monthlyGrowth: "12%", score: 88, growthProbability: 85, investmentReadiness: "High", riskLevel: "Medium", aiRecommendation: "Defensible IP and strong B2B contracts. Solid bet.", verifiedFounder: true },
  { id: "ent-008", name: "Aisha Mohammed", photoUrl: "https://i.pravatar.cc/150?u=aisha", startupName: "LogiChain", startupStage: "Seed", pitchSummary: "Blockchain verified supply chain for halal products.", industry: "Logistics", marketSize: "$20B SAM", tractionMetrics: "$8k MRR", teamSize: 7, revenueStatus: "Post-revenue", monthlyGrowth: "18%", score: 72, growthProbability: 65, investmentReadiness: "Moderate", riskLevel: "Medium", aiRecommendation: "Good early adoption but faces regulatory hurdles.", verifiedFounder: true },
  { id: "ent-009", name: "Carlos Mateo", photoUrl: "https://i.pravatar.cc/150?u=carlos", startupName: "VR-Therapy", startupStage: "Pre-seed", pitchSummary: "VR exposure therapy for anxiety disorders.", industry: "HealthTech / VR", marketSize: "$4B SAM", tractionMetrics: "2 clinics targeting FDA approval", teamSize: 3, revenueStatus: "Pre-revenue", monthlyGrowth: "0%", score: 68, growthProbability: 60, investmentReadiness: "Moderate", riskLevel: "High", aiRecommendation: "High risk due to clinical trials. Long time to market.", verifiedFounder: false },
  { id: "ent-010", name: "Jessica Fox", photoUrl: "https://i.pravatar.cc/150?u=jessica", startupName: "CodeCompanion", startupStage: "Seed", pitchSummary: "AI rubber duck debugging tool for junior devs.", industry: "DevTools / AI", marketSize: "$6B SAM", tractionMetrics: "$30k MRR", teamSize: 4, revenueStatus: "Post-revenue", monthlyGrowth: "40%", score: 90, growthProbability: 88, investmentReadiness: "High", riskLevel: "Low", aiRecommendation: "Exceptional organic growth loop. Immediate investment target.", verifiedFounder: true },
  { id: "ent-011", name: "Tyler Brooks", photoUrl: "https://i.pravatar.cc/150?u=tyler", startupName: "StreamSec", startupStage: "Series A", pitchSummary: "Real-time threat detection for live video streams.", industry: "Cybersecurity", marketSize: "$18B SAM", tractionMetrics: "$110k MRR", teamSize: 30, revenueStatus: "Post-revenue", monthlyGrowth: "14%", score: 94, growthProbability: 92, investmentReadiness: "High", riskLevel: "Low", aiRecommendation: "Enterprise dominance in niche. Very strong metrics.", verifiedFounder: true },
  { id: "ent-012", name: "Nadia Kozlov", photoUrl: "https://i.pravatar.cc/150?u=nadia", startupName: "EcoPack", startupStage: "Seed", pitchSummary: "Biodegradable mushroom-based packaging for D2C brands.", industry: "ClimateTech / D2C", marketSize: "$22B SAM", tractionMetrics: "$12k MRR", teamSize: 9, revenueStatus: "Post-revenue", monthlyGrowth: "20%", score: 81, growthProbability: 75, investmentReadiness: "High", riskLevel: "Medium", aiRecommendation: "Strong ESG narrative and early B2B pilots are promising.", verifiedFounder: true },
  { id: "ent-013", name: "Jordan Lee", photoUrl: "https://i.pravatar.cc/150?u=jordan", startupName: "RentRadar", startupStage: "Pre-seed", pitchSummary: "Aggregating unlisted rental properties using AI.", industry: "PropTech", marketSize: "$14B SAM", tractionMetrics: "10k waitlist", teamSize: 2, revenueStatus: "Pre-revenue", monthlyGrowth: "N/A", score: 70, growthProbability: 62, investmentReadiness: "Moderate", riskLevel: "Medium", aiRecommendation: "Good consumer demand signal but scraping viability is questionable.", verifiedFounder: false },
  { id: "ent-014", name: "Mia Santos", photoUrl: "https://i.pravatar.cc/150?u=mia", startupName: "PetWell", startupStage: "Seed", pitchSummary: "Subscription telehealth specifically for exotic pets.", industry: "HealthTech / Consumer", marketSize: "$2B SAM", tractionMetrics: "$5k MRR", teamSize: 3, revenueStatus: "Post-revenue", monthlyGrowth: "15%", score: 64, growthProbability: 58, investmentReadiness: "Low", riskLevel: "Medium", aiRecommendation: "Niche is too small for VC scale. Better lifestyle business.", verifiedFounder: true },
  { id: "ent-015", name: "Wei Chen", photoUrl: "https://i.pravatar.cc/150?u=weichen", startupName: "QuantumDB", startupStage: "Series B", pitchSummary: "Database optimized for quantum computing environments.", industry: "DeepTech / Infrastructure", marketSize: "$40B SAM", tractionMetrics: "$500k MRR", teamSize: 85, revenueStatus: "Post-revenue", monthlyGrowth: "10%", score: 96, growthProbability: 95, investmentReadiness: "High", riskLevel: "Low", aiRecommendation: "Category defining technology. Strategic investment.", verifiedFounder: true },
  { id: "ent-016", name: "Lucas Müller", photoUrl: "https://i.pravatar.cc/150?u=lucas", startupName: "ShiftDesk", startupStage: "Seed", pitchSummary: "Workforce management for deskless shift workers.", industry: "SaaS / HR", marketSize: "$9B SAM", tractionMetrics: "$22k MRR", teamSize: 7, revenueStatus: "Post-revenue", monthlyGrowth: "28%", score: 86, growthProbability: 82, investmentReadiness: "High", riskLevel: "Low", aiRecommendation: "High retention rates. Clear path to Series A.", verifiedFounder: true },
  { id: "ent-017", name: "Amina Diallo", photoUrl: "https://i.pravatar.cc/150?u=amina", startupName: "PaySwap", startupStage: "Pre-seed", pitchSummary: "Cross-border B2B payments optimized for African corridors.", industry: "FinTech", marketSize: "$30B SAM", tractionMetrics: "$2k MRR", teamSize: 4, revenueStatus: "Post-revenue", monthlyGrowth: "50%", score: 75, growthProbability: 70, investmentReadiness: "Moderate", riskLevel: "Medium", aiRecommendation: "Massive market but high regulatory execution risk.", verifiedFounder: false },
  { id: "ent-018", name: "Samir Gupta", photoUrl: "https://i.pravatar.cc/150?u=samir", startupName: "AutoInspect", startupStage: "Series A", pitchSummary: "Computer vision for manufacturing defect detection.", industry: "AI / Industrial", marketSize: "$12B SAM", tractionMetrics: "$180k MRR", teamSize: 22, revenueStatus: "Post-revenue", monthlyGrowth: "8%", score: 91, growthProbability: 88, investmentReadiness: "High", riskLevel: "Low", aiRecommendation: "Sticky enterprise contracts. Solid revenue base.", verifiedFounder: true },
  { id: "ent-019", name: "Olivia Thomas", photoUrl: "https://i.pravatar.cc/150?u=oliviat", startupName: "GlowUp", startupStage: "Seed", pitchSummary: "AI driven personalized skincare formulation.", industry: "D2C / AI", marketSize: "$16B SAM", tractionMetrics: "$45k MRR", teamSize: 10, revenueStatus: "Post-revenue", monthlyGrowth: "20%", score: 83, growthProbability: 78, investmentReadiness: "High", riskLevel: "Medium", aiRecommendation: "CAC is slightly high, but LTV makes unit economics work.", verifiedFounder: true },
  { id: "ent-020", name: "Ben Horowitz II", photoUrl: "https://i.pravatar.cc/150?u=ben", startupName: "ChainGov", startupStage: "Seed", pitchSummary: "DAO governance tooling for traditional corporations.", industry: "Crypto / SaaS", marketSize: "$5B SAM", tractionMetrics: "$0 MRR", teamSize: 5, revenueStatus: "Pre-revenue", monthlyGrowth: "0%", score: 55, growthProbability: 40, investmentReadiness: "Low", riskLevel: "High", aiRecommendation: "Market timing seems wrong. Needs strong pivot.", verifiedFounder: true },
  { id: "ent-021", name: "Yuki Sato", photoUrl: "https://i.pravatar.cc/150?u=yuki", startupName: "RoboChef", startupStage: "Series A", pitchSummary: "Automated modular kitchens for quick-service restaurants.", industry: "Hardware / FoodTech", marketSize: "$25B SAM", tractionMetrics: "$90k MRR", teamSize: 40, revenueStatus: "Post-revenue", monthlyGrowth: "15%", score: 89, growthProbability: 84, investmentReadiness: "High", riskLevel: "Medium", aiRecommendation: "Capital intensive but solves a massive labor shortage issue.", verifiedFounder: true }
];

export const mockPosts: SocialPost[] = [
  { id: "post-101", authorId: "inv-001", authorName: "Alexia Rossi", authorPhoto: "https://i.pravatar.cc/150?u=alexiarossi", authorRole: "investor", authorHeadline: "Partner @ Apex Ventures", content: "We're actively looking to deploy $5M in open-source AI tooling this quarter. If you're building next-gen developer tools with >$5k MRR, send your deck! 🚀", postType: "Funding Opportunity", tags: ["AI", "OpenSource", "Funding"], upvotes: 142, comments: [{ id: "c-1", authorId: "ent-001", authorName: "Sarah Jenkins", authorPhoto: "https://i.pravatar.cc/150?u=sarahj", authorRole: "founder", text: "Just sent over the NexusAI deck! Our OSS framework has 5k GitHub stars.", timestamp: "2 hours ago" }], timestamp: "5 hours ago" },
  { id: "post-102", authorId: "ent-001", authorName: "Sarah Jenkins", authorPhoto: "https://i.pravatar.cc/150?u=sarahj", authorRole: "founder", authorHeadline: "Founder @ NexusAI", content: "Just crossed $15k MRR! The biggest lesson learned: Don't optimize for self-serve too early. Doing concierge onboarding for our first 20 B2B customers gave us the exact feature roadmap we needed.", postType: "Growth Advice", tags: ["SaaS", "Growth", "Milestone"], upvotes: 89, comments: [], timestamp: "1 day ago" },
  { id: "post-103", authorId: "inv-003", authorName: "Daniel Kapoor", authorPhoto: "https://i.pravatar.cc/150?u=danielk", authorRole: "investor", authorHeadline: "Managing Director @ Kapoor Capital", content: "Every founder pitching crypto right now needs to focus on compliance first, tech second. The landscape has changed. Too many decks ignoring regulatory reality.", postType: "Market Trend", tags: ["Crypto", "FinTech", "Advice"], upvotes: 215, comments: [], timestamp: "3 hours ago" },
  { id: "post-104", authorId: "ent-010", authorName: "Jessica Fox", authorPhoto: "https://i.pravatar.cc/150?u=jessica", authorRole: "founder", authorHeadline: "Founder @ CodeCompanion", content: "Product launch day! CodeCompanion is now live on ProductHunt. We've built an AI rubber duck for junior devs. Check it out and let me know your thoughts!", postType: "Product Launch", tags: ["Launch", "AI", "DevTools"], upvotes: 350, comments: [], timestamp: "6 hours ago" },
  { id: "post-105", authorId: "ent-003", authorName: "Aarav Patel", authorPhoto: "https://i.pravatar.cc/150?u=aarav", authorRole: "founder", authorHeadline: "CEO @ FinPulse", content: "We are officially raising our Series A! Looking for lead investors with deep experience in SEA FinTech. Our deck is ready in the data room.", postType: "Pitch Request", tags: ["SeriesA", "FinTech", "Fundraising"], upvotes: 112, comments: [], timestamp: "1 day ago" },
  { id: "post-106", authorId: "inv-006", authorName: "Priya Mehta", authorPhoto: "https://i.pravatar.cc/150?u=priyam", authorRole: "investor", authorHeadline: "General Partner @ NextGen VC", content: "AMA: I'm a GP at a $100M ClimateTech fund. Ask me anything about what we look for in seed-stage hardware deals.", postType: "AMA", tags: ["AMA", "ClimateTech", "Seed"], upvotes: 420, comments: [], timestamp: "2 days ago" },
  { id: "post-107", authorId: "inv-002", authorName: "Marcus Chen", authorPhoto: "https://i.pravatar.cc/150?u=marcuschen", authorRole: "investor", authorHeadline: "Angel Investor", content: "Hot take: EdTech is making a massive comeback this year, but only for neurodivergent and personalized AI tools. Mass-market courses are dead.", postType: "Market Trend", tags: ["EdTech", "AI", "HotTake"], upvotes: 95, comments: [], timestamp: "4 hours ago" },
  { id: "post-108", authorId: "ent-012", authorName: "Nadia Kozlov", authorPhoto: "https://i.pravatar.cc/150?u=nadia", authorRole: "founder", authorHeadline: "Founder @ EcoPack", content: "Just signed our first enterprise pilot with a Fortune 500 D2C brand! Biodegradable mushroom packaging is the future.", postType: "Startup Win", tags: ["ClimateTech", "Milestone", "B2B"], upvotes: 275, comments: [], timestamp: "12 hours ago" },
  { id: "post-109", authorId: "ent-006", authorName: "Emma Watson", authorPhoto: "https://i.pravatar.cc/150?u=emma", authorRole: "founder", authorHeadline: "Founder @ CreatorKit", content: "Has anyone successfully transitioned from a usage-based pricing model back to standard SaaS tiers? Finding usage-based too unpredictable for our MRR metrics.", postType: "Founder Question", tags: ["SaaS", "Pricing", "Advice needed"], upvotes: 68, comments: [], timestamp: "2 hours ago" },
  { id: "post-110", authorId: "inv-010", authorName: "Samantha Lee", authorPhoto: "https://i.pravatar.cc/150?u=samantha", authorRole: "investor", authorHeadline: "Managing Partner @ Lee & Co Ventures", content: "I review 50 pitch decks a week. The #1 mistake? Not clearly defining the SAM (Serviceable Addressable Market). Saying 'the AI market is $1 Trillion' tells me nothing about your specific business.", postType: "Growth Advice", tags: ["Pitching", "VC", "Advice"], upvotes: 512, comments: [], timestamp: "1 day ago" },
  { id: "post-111", authorId: "inv-015", authorName: "Isabella Cruz", authorPhoto: "https://i.pravatar.cc/150?u=isabella", authorRole: "investor", authorHeadline: "Partner @ Latam Future Fund", content: "Latam FinTech is still heavily underinvested compared to the population growth and smartphone penetration. Looking at 3 new deals this week alone in Bogota.", postType: "Market Trend", tags: ["Latam", "FinTech", "Investing"], upvotes: 180, comments: [], timestamp: "5 hours ago" },
  { id: "post-112", authorId: "ent-016", authorName: "Lucas Müller", authorPhoto: "https://i.pravatar.cc/150?u=lucas", authorRole: "founder", authorHeadline: "Founder @ ShiftDesk", content: "Poll: Founders, what is your biggest bottleneck right now? 1. Engineering talent. 2. Top-of-funnel leads. 3. Closing enterprise deals. 4. Fundraising.", postType: "Poll", tags: ["Poll", "Founders", "Challenges"], upvotes: 132, comments: [], timestamp: "8 hours ago" }
];

export const mockMessages = [
  { id: "msg-1", participants: ["inv-001", "ent-001"], lastMessage: "Let's schedule a call next Tuesday.", unread: 1, timestamp: "2 hours ago" },
  { id: "msg-2", participants: ["inv-002", "ent-010"], lastMessage: "I love the CodeCompanion ProductHunt launch. Could you send the deck?", unread: 0, timestamp: "1 day ago" },
  { id: "msg-3", participants: ["inv-006", "ent-012"], lastMessage: "Checking in on the enterprise pilot progress.", unread: 0, timestamp: "3 days ago" },
  { id: "msg-4", participants: ["inv-003", "ent-003"], lastMessage: "We are reviewing your data room now. Thanks Aarav.", unread: 0, timestamp: "1 week ago" }
];
